// EXPORT/CODEGENERATOR.JS
//
// GENERATES A FULLY STANDALONE HTML FILE FROM THE CURRENT SCENE.
// VARIABLE NAMES IN THE OUTPUT ARE DERIVED FROM LAYER/TRACK NAMES FOR READABILITY.
// EFFECTS (GLITCH, HUESHIFT, INVERT) ARE BAKED IN PER-LAYER / PER-TRACK.

// ── NAME SANITIZATION ─────────────────────────────────────────────────────────
// CONVERTS A HUMAN NAME LIKE "STARS BG" → "STARSBG", "MAP LOOP!" → "MAPLOOP"
function toVarName(name) {
  return name
    .trim()
    .replace(/[^a-zA-Z0-9 _]/g, "")   // STRIP NON-ALPHANUMERIC EXCEPT SPACE/UNDERSCORE
    .replace(/\s+(.)/g, (_, c) => c.toUpperCase()) // CAMELCASE ON SPACES
    .replace(/\s/g, "_")
    .replace(/^[0-9]/, "_$&")          // CAN'T START WITH A DIGIT
    || "layer";
}

// BUILD A DEDUPLICATED VARNAME MAP FOR ALL LAYERS AND THEIR TRACKS.
// IF TWO LAYERS HAVE THE SAME SANITIZED NAME, APPEND _2, _3, ETC.
function buildVarMap(layers) {
  const map = {};       // ID → VARNAME
  const usedNames = {}; // VARNAME → COUNT

  const assign = (id, rawName) => {
    let base = toVarName(rawName);
    if (!usedNames[base]) {
      usedNames[base] = 1;
      map[id] = base;
    } else {
      usedNames[base]++;
      map[id] = `${base}_${usedNames[base]}`;
    }
  };

  layers.forEach((l) => {
    assign(l.id, l.name);
    // ALSO ASSIGN NAMES FOR TRACKS
    (l.config?.tracks || []).forEach((t) => assign(t.id, t.name));
  });

  return map;
}

// ── MAIN EXPORT FUNCTION ──────────────────────────────────────────────────────
export function generateCode(layers, bgColor) {
  const visLayers = layers.filter((l) => l.visible);
  const varMap = buildVarMap(visLayers);
  const v = (id) => varMap[id] || id; // SHORTHAND: V(LAYER.ID) → "STARSBG"

  const lines = [];

  // ── HTML BOILERPLATE ────────────────────────────────────────────────────────
  lines.push(`<!DOCTYPE html>`);
  lines.push(`<html>\n<head>\n<meta charset="UTF-8">`);
  lines.push(`<style>`);
  lines.push(`  body { margin: 0; background: ${bgColor}; overflow: hidden; }`);
  lines.push(`  canvas { display: block; width: 100vw; height: 100vh; }`);
  lines.push(`</style>\n</head>\n<body>`);
  lines.push(`<canvas id="c"></canvas>`);
  lines.push(`<script>`);
  lines.push(`// GENERATED BY ONION STUDIO PRO`);
  lines.push(`// PLACE SPRITE SHEET IMAGES IN THE SAME DIRECTORY AS THIS HTML FILE.`);
  lines.push(`const canvas = document.getElementById('c');`);
  lines.push(`const ctx = canvas.getContext('2d');`);
  lines.push(`canvas.width = window.innerWidth;`);
  lines.push(`canvas.height = window.innerHeight;`);
  lines.push(`window.addEventListener('resize', () => { canvas.width = window.innerWidth; canvas.height = window.innerHeight; });`);
  lines.push(``);

  // ── EFFECT HELPERS (ONLY EMITTED IF ACTUALLY USED) ──────────────────────────
  const usedEffects = collectUsedEffects(visLayers);
  if (usedEffects.has("glitch"))   lines.push(...glitchHelperCode());
  if (usedEffects.has("hueShift")) lines.push(...hueShiftHelperCode());
  if (usedEffects.has("invert"))   lines.push(...invertHelperCode());

  // ── SPRITE IMAGE DECLARATIONS ───────────────────────────────────────────────
  visLayers.forEach((l) => {
    if (l.type !== "sprite" || !l.config.src) return;
    const imgPath = l.config.srcName || "sprite.png";
    lines.push(`const img_${v(l.id)} = new Image();`);
    lines.push(`img_${v(l.id)}.src = "./${imgPath}";`);
    lines.push(``);
  });

  // ── PARTICLE DECLARATIONS ───────────────────────────────────────────────────
  visLayers.forEach((l) => {
    if (l.type !== "particle") return;
    const c = l.config;
    lines.push(`// PARTICLE LAYER: ${l.name}`);
    lines.push(`const ${v(l.id)} = [];`);
    lines.push(`for (let i = 0; i < ${c.count}; i++) {`);
    lines.push(`  ${v(l.id)}.push({`);
    lines.push(`    x: Math.random() * canvas.width,`);
    lines.push(`    y: Math.random() * canvas.height,`);
    lines.push(`    vx: (Math.random() - 0.5) * ${c.speedX},`);
    lines.push(`    vy: -(Math.random() * ${c.speedY} + 0.5),`);
    lines.push(`    size: Math.random() * ${c.size} + 1,`);
    lines.push(`    alpha: Math.random() * 0.6 + 0.3,`);
    lines.push(`    life: Math.random(),`);
    lines.push(`  });`);
    lines.push(`}`);
    lines.push(``);
  });

  // ── SPRITE TRACK PLAYBACK STATE ─────────────────────────────────────────────
  visLayers.forEach((l) => {
    if (l.type !== "sprite") return;
    (l.config.tracks || []).forEach((track) => {
      if (!track.enabled) return;
      lines.push(`// TRACK: ${l.name} / ${track.name}`);
      lines.push(`let frame_${v(track.id)} = 0;`);
      lines.push(`let elapsed_${v(track.id)} = 0;`);
    });
  });
  lines.push(``);

  // ── GLITCH STATE DECLARATIONS ───────────────────────────────────────────────
  if (usedEffects.has("glitch")) {
    visLayers.forEach((l) => {
      getEffectSources(l).forEach(({ id, effects }) => {
        const glitch = effects.find((e) => e.type === "glitch");
        if (!glitch) return;
        lines.push(`let glitchTimer_${v(id)} = 0;`);
        lines.push(`let glitchBands_${v(id)} = [];`);
        lines.push(`let glitchInterval_${v(id)} = ${800 - glitch.speed * 760};`);
      });
    });
    lines.push(``);
  }

  // ── MAIN LOOP ───────────────────────────────────────────────────────────────
  lines.push(`let last = 0;`);
  lines.push(`function loop(t) {`);
  lines.push(`  const dt = t - last; last = t;`);
  lines.push(`  ctx.clearRect(0, 0, canvas.width, canvas.height);`);
  lines.push(`  ctx.fillStyle = '${bgColor}';`);
  lines.push(`  ctx.fillRect(0, 0, canvas.width, canvas.height);`);
  lines.push(``);

  visLayers.forEach((l) => {
    if (l.type === "particle") {
      lines.push(...particleLoopCode(l, v));
    } else if (l.type === "sprite") {
      lines.push(...spriteLoopCode(l, v));
    }
  });

  lines.push(`  ctx.globalAlpha = 1;`);
  lines.push(`  ctx.globalCompositeOperation = 'source-over';`);
  lines.push(`  requestAnimationFrame(loop);`);
  lines.push(`}`);
  lines.push(`requestAnimationFrame(loop);`);
  lines.push(`<\/script>\n</body>\n</html>`);

  return lines.join("\n");
}

// ── HELPERS ───────────────────────────────────────────────────────────────────

function collectUsedEffects(layers) {
  const used = new Set();
  layers.forEach((l) => {
    (l.effects || []).forEach((e) => used.add(e.type));
    if (l.type === "sprite") {
      (l.config.tracks || []).forEach((t) => {
        (t.effects || []).forEach((e) => used.add(e.type));
      });
    }
  });
  return used;
}

function getEffectSources(layer) {
  if (layer.type === "particle") {
    return [{ id: layer.id, effects: layer.effects || [] }];
  }
  return (layer.config.tracks || [])
    .filter((t) => t.enabled)
    .map((t) => ({ id: t.id, effects: t.effects || [] }));
}

// ── PARTICLE LOOP CODE ────────────────────────────────────────────────────────
function particleLoopCode(l, v) {
  const c = l.config;
  const effects = l.effects || [];
  const hasEffects = effects.length > 0;
  const varName = v(l.id);
  const lines = [];

  lines.push(`  // ${l.name}`);

  if (hasEffects) {
    lines.push(`  (function() {`);
    lines.push(`    const off = document.createElement('canvas');`);
    lines.push(`    off.width = canvas.width; off.height = canvas.height;`);
    lines.push(`    const offCtx = off.getContext('2d');`);
    lines.push(`    ${varName}.forEach(p => {`);
    lines.push(`      p.x += p.vx; p.y += p.vy; p.life -= 0.002;`);
    lines.push(`      if (p.y < -5 || p.life <= 0) { p.x = Math.random()*canvas.width; p.y = canvas.height+5; p.life = Math.random(); }`);
    lines.push(`      offCtx.globalAlpha = p.alpha * Math.max(0, p.life * 2);`);
    lines.push(`      offCtx.fillStyle = '${c.color}';`);
    lines.push(`      offCtx.beginPath(); offCtx.arc(p.x, p.y, p.size, 0, Math.PI*2); offCtx.fill();`);
    lines.push(`    });`);
    lines.push(...applyEffectsCode("offCtx", "off", effects, l.id, v, "    "));
    lines.push(`    ctx.drawImage(off, 0, 0);`);
    lines.push(`  })();`);
  } else {
    lines.push(`  ${varName}.forEach(p => {`);
    lines.push(`    p.x += p.vx; p.y += p.vy; p.life -= 0.002;`);
    lines.push(`    if (p.y < -5 || p.life <= 0) { p.x = Math.random()*canvas.width; p.y = canvas.height+5; p.life = Math.random(); }`);
    lines.push(`    ctx.globalAlpha = p.alpha * Math.max(0, p.life * 2);`);
    lines.push(`    ctx.fillStyle = '${c.color}';`);
    lines.push(`    ctx.beginPath(); ctx.arc(p.x, p.y, p.size, 0, Math.PI*2); ctx.fill();`);
    lines.push(`  });`);
  }

  lines.push(``);
  return lines;
}

// ── SPRITE LOOP CODE ──────────────────────────────────────────────────────────
function spriteLoopCode(l, v) {
  const c = l.config;
  const tracks = (c.tracks || []).filter((t) => t.enabled);
  const imgVar = `img_${v(l.id)}`;
  const lines = [];

  lines.push(`  // ${l.name}`);
  lines.push(`  if (${imgVar}.complete) {`);
  lines.push(`    const cols_${v(l.id)} = Math.max(1, Math.floor(${imgVar}.width / ${c.frameW}));`);

  tracks.forEach((track) => {
    const frames = JSON.stringify(track.frames || [0]);
    const fps = track.fps || 12;
    const frameVar    = `frame_${v(track.id)}`;
    const elapsedVar  = `elapsed_${v(track.id)}`;
    const opacity     = track.opacity ?? 1;
    const blend       = track.blendMode || "source-over";
    const effects     = track.effects || [];
    const hasEffects  = effects.length > 0;
    const framesVar   = `frames_${v(track.id)}`;
    const colVar      = `col_${v(track.id)}`;
    const rowVar      = `row_${v(track.id)}`;

    lines.push(``);
    lines.push(`    // TRACK: ${track.name}`);
    lines.push(`    ${elapsedVar} += dt;`);
    lines.push(`    if (${elapsedVar} >= ${(1000 / fps).toFixed(2)}) {`);
    lines.push(`      ${elapsedVar} = 0;`);
    lines.push(`      const ${framesVar} = ${frames};`);
    if (track.loop) {
      lines.push(`      ${frameVar} = (${frameVar} + 1) % ${framesVar}.length;`);
    } else {
      lines.push(`      if (${frameVar} < ${framesVar}.length - 1) ${frameVar}++;`);
    }
    lines.push(`    }`);

    // DRAW
    lines.push(`    (function() {`);
    lines.push(`      const ${framesVar} = ${frames};`);
    lines.push(`      const fi = ${framesVar}[${frameVar}];`);
    lines.push(`      const ${colVar} = fi % cols_${v(l.id)};`);
    lines.push(`      const ${rowVar} = Math.floor(fi / cols_${v(l.id)});`);

    if (hasEffects) {
      lines.push(`      const off = document.createElement('canvas');`);
      lines.push(`      off.width = canvas.width; off.height = canvas.height;`);
      lines.push(`      const offCtx = off.getContext('2d');`);
      lines.push(`      offCtx.drawImage(${imgVar},`);
      lines.push(`        ${colVar} * ${c.frameW}, ${rowVar} * ${c.frameH}, ${c.frameW}, ${c.frameH},`);
      lines.push(`        ${c.x || 0}, ${c.y || 0}, ${c.frameW} * ${c.scale || 1}, ${c.frameH} * ${c.scale || 1});`);
      lines.push(...applyEffectsCode("offCtx", "off", effects, track.id, v, "      "));
      lines.push(`      ctx.save();`);
      lines.push(`      ctx.globalAlpha = ${opacity};`);
      lines.push(`      ctx.globalCompositeOperation = '${blend}';`);
      lines.push(`      ctx.drawImage(off, 0, 0);`);
      lines.push(`      ctx.restore();`);
    } else {
      lines.push(`      ctx.save();`);
      lines.push(`      ctx.globalAlpha = ${opacity};`);
      lines.push(`      ctx.globalCompositeOperation = '${blend}';`);
      lines.push(`      ctx.drawImage(${imgVar},`);
      lines.push(`        ${colVar} * ${c.frameW}, ${rowVar} * ${c.frameH}, ${c.frameW}, ${c.frameH},`);
      lines.push(`        ${c.x || 0}, ${c.y || 0}, ${c.frameW} * ${c.scale || 1}, ${c.frameH} * ${c.scale || 1});`);
      lines.push(`      ctx.restore();`);
    }
    lines.push(`    })();`);
  });

  lines.push(`  }`);
  lines.push(``);
  return lines;
}

// ── EFFECT APPLICATION CODE ───────────────────────────────────────────────────
function applyEffectsCode(ctxVar, canvasVar, effects, id, v, indent = "  ") {
  const lines = [];
  effects.forEach((effect) => {
    if (effect.type === "invert") {
      lines.push(`${indent}applyInvert(${ctxVar}, ${canvasVar}, ${effect.amount ?? 1});`);
    } else if (effect.type === "hueShift") {
      lines.push(`${indent}applyHueShift(${ctxVar}, ${canvasVar}, ${effect.hue ?? 0}, ${effect.saturation ?? 1}, ${effect.brightness ?? 1});`);
    } else if (effect.type === "glitch") {
      const stateVar = v(id);
      lines.push(`${indent}applyGlitch(${ctxVar}, ${canvasVar}, ${effect.intensity ?? 0.5}, ${effect.speed ?? 0.5}, glitchTimer_${stateVar}, glitchBands_${stateVar}, dt);`);
      lines.push(`${indent}glitchTimer_${stateVar} += dt;`);
      lines.push(`${indent}if (glitchTimer_${stateVar} >= glitchInterval_${stateVar}) { glitchTimer_${stateVar} = 0; glitchBands_${stateVar} = []; }`);
    }
  });
  return lines;
}

// ── EFFECT HELPER EMITTERS ────────────────────────────────────────────────────

function invertHelperCode() {
  return [
    `// EFFECT: INVERT`,
    `function applyInvert(ctx, canvas, amount) {`,
    `  const snap = document.createElement('canvas');`,
    `  snap.width = canvas.width; snap.height = canvas.height;`,
    `  snap.getContext('2d').drawImage(canvas, 0, 0);`,
    `  ctx.clearRect(0, 0, canvas.width, canvas.height);`,
    `  ctx.filter = \`invert(\${amount})\`;`,
    `  ctx.drawImage(snap, 0, 0);`,
    `  ctx.filter = 'none';`,
    `}`,
    ``,
  ];
}

function hueShiftHelperCode() {
  return [
    `// EFFECT: HUE SHIFT`,
    `function applyHueShift(ctx, canvas, hue, saturation, brightness) {`,
    `  const filterParts = [];`,
    `  if (hue !== 0) filterParts.push(\`hue-rotate(\${hue}deg)\`);`,
    `  if (saturation !== 1) filterParts.push(\`saturate(\${saturation})\`);`,
    `  if (brightness !== 1) filterParts.push(\`brightness(\${brightness})\`);`,
    `  if (filterParts.length === 0) return;`,
    `  const snap = document.createElement('canvas');`,
    `  snap.width = canvas.width; snap.height = canvas.height;`,
    `  snap.getContext('2d').drawImage(canvas, 0, 0);`,
    `  ctx.clearRect(0, 0, canvas.width, canvas.height);`,
    `  ctx.filter = filterParts.join(' ');`,
    `  ctx.drawImage(snap, 0, 0);`,
    `  ctx.filter = 'none';`,
    `}`,
    ``,
  ];
}

function glitchHelperCode() {
  return [
    `// EFFECT: GLITCH`,
    `function applyGlitch(ctx, canvas, intensity, speed, timer, bands, dt) {`,
    `  if (intensity === 0) return;`,
    `  if (bands.length === 0) {`,
    `    const count = Math.floor(3 + intensity * 12);`,
    `    for (let i = 0; i < count; i++) {`,
    `      bands.push({`,
    `        y: Math.random() * canvas.height,`,
    `        h: Math.random() * canvas.height * 0.08 * intensity + 2,`,
    `        offset: (Math.random() - 0.5) * intensity * 80,`,
    `        flash: Math.random() < intensity * 0.3,`,
    `        alpha: Math.random() * 0.6 + 0.1,`,
    `      });`,
    `    }`,
    `  }`,
    `  const split = intensity * 12;`,
    `  const rOff = (Math.random() - 0.5) * split;`,
    `  const bOff = (Math.random() - 0.5) * split;`,
    `  if (Math.abs(rOff) > 0.5 || Math.abs(bOff) > 0.5) {`,
    `    ctx.save();`,
    `    ctx.globalAlpha = 0.35;`,
    `    ctx.globalCompositeOperation = 'screen';`,
    `    ctx.drawImage(canvas, rOff, 0);`,
    `    ctx.drawImage(canvas, -bOff, 2);`,
    `    ctx.globalCompositeOperation = 'source-over';`,
    `    ctx.restore();`,
    `  }`,
    `  ctx.save();`,
    `  bands.forEach(b => {`,
    `    if (Math.abs(b.offset) < 0.5) return;`,
    `    ctx.save();`,
    `    ctx.beginPath(); ctx.rect(0, b.y, canvas.width, b.h); ctx.clip();`,
    `    ctx.clearRect(0, b.y, canvas.width, b.h);`,
    `    ctx.drawImage(canvas, 0, b.y, canvas.width, b.h, b.offset, b.y, canvas.width, b.h);`,
    `    if (b.flash) {`,
    `      ctx.globalAlpha = b.alpha * intensity;`,
    `      ctx.fillStyle = Math.random() > 0.5 ? '#ffffff' : '#00ffff';`,
    `      ctx.fillRect(0, b.y, canvas.width, b.h);`,
    `    }`,
    `    ctx.restore();`,
    `  });`,
    `  ctx.restore();`,
    `  if (intensity > 0.6 && Math.random() < intensity * 0.04) {`,
    `    ctx.save();`,
    `    ctx.globalAlpha = 0.08 * intensity;`,
    `    ctx.fillStyle = '#00ffff';`,
    `    ctx.fillRect(0, 0, canvas.width, canvas.height);`,
    `    ctx.restore();`,
    `  }`,
    `}`,
    ``,
  ];
}